spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/promesa
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      data-locations: classpath:data.sql
      mode: always

logging:
  level:
    org.hibernate.SQL: DEBUG